### ISSUE TITLE
proxy masquerading not working

### ISSUE THREAD

**Issue by woyczek** [jonasmalacofilho/git-cache-http-server#18]
When the git-cache-http-server is behind a proxy, it cannot be defined.

An option to redirect git caching thru the proxy is missing.

**Comment by jonasmalacofilho** [comment]
Can you please elaborate a bit?  What options and features would you need beyond what was implemented in #14?

**Comment by woyczek** [comment]
Oh…
Didn’t read the source code the right way.

**Comment by woyczek** [comment]
In fact, it is not as clear as said in #14.

```
  # export | grep http
  declare -x http_proxy="http://10.17.17.5:3128"
  declare -x https_proxy="http://10.17.17.5:3128"

  # dig +short www.forge.internal.fr
  10.19.1.23

  # git-cache-http-server --port 1234 --cache-dir /home/git-cache &

  […]
  GET /dummy_user@www.forge.internal.fr/plugins/git/local.repository.git/info/refs?service=git-upload-pack
  authenticating on the upstream repo
    events.js:160
        throw er; // Unhandled 'error' event
        ^

  Error: connect ETIMEDOUT 10.19.1.23:443
      at Object.exports._errnoException (util.js:1020:11)
      at exports._exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
```

**Comment by woyczek** [comment]
Oh… found.
The release is completely out of date.
We have to build it from sources.

Is it possible to provide a new release, as the build process is not as trivial as it appears ?

**Comment by jonasmalacofilho** [comment]
> Is it possible to provide a new release, as the build process is not as trivial as it appears ?

Sure, I'll try to do that.

But you should™ also be able to install/use directly from this git repository.  The built JS in `bin/` is generally kept up-to-date with the sources in `src/` (in Haxe).

**Comment by jonasmalacofilho** [comment]
The build process has been updated and should be fairly easy to follow these days.
