### ISSUE TITLE
`git fetch --prune` does not prune deleted remote branches

### ISSUE THREAD

**Issue by gurjeet** [jonasmalacofilho/git-cache-http-server#21]
I think the solution is to do a prune on the cache after every fetch. Following is a reproducible test-case.

```
$ git-cache-http-server -c /tmp/git-cache-test/ &
$ git clone http://localhost:8080/github.com/gurjeet/home
$ cd home/
$ git remote set-url --push origin git@github.com:gurjeet/home.git
$ git checkout -b del
$ git push origin del
$ git checkout master
$ git branch -r
  origin/HEAD -> origin/master
  origin/del
...
# Now delete remote branch named `del`
$ git push origin :del
To github.com:gurjeet/home.git
 - [deleted]         del
#The branch reappears even though we asked for pruning
$ git fetch --prune
From http://localhost:8080/github.com/gurjeet/home
 * [new branch]      del        -> origin/del

# Set the non-cache, direct URL and watch the remote reference being deleted; the expected behaviour
$ git remote set-url origin git@github.com:gurjeet/home.git
$ git fetch --prune
From github.com:gurjeet/home
 - [deleted]         (none)     -> origin/del
```

**Comment by jonasmalacofilho** [comment]
Thanks for reporting this.  I think your proposed solution makes sense and should work.

I'll certainly include a fix when I get a chance to work a bit on this code.  In the meantime, I would very much appreciate a pull request.

**Comment by gurjeet** [comment]
@jonasmalacofilho I have created PR #22 that passes my test case above.

In addition to pruning deleted branches, I have also added the option to prune tags (`--prune-tags`). I read through the man-pages of `git-fetch`, and I think deleting tags as well is the right thing to do to maintain the consistency of the cache.

**Comment by jonasmalacofilho** [comment]
Thanks again!
