### ISSUE TITLE
Use http_proxy to fetch from upstream

### ISSUE THREAD

**Issue by mpfz0r** [jonasmalacofilho/git-cache-http-server#4]
Hi,

I was wondering whether it's supported to use a proxy for git-cache-http-server
itself.

Starting it with
`$ http_proxy=http://my-proxy:8888 git-cache-http-server
`
seems to have no effect.

Thanks!

**Comment by jonasmalacofilho** [comment]
This really isn't supported just yet.  I'll look into adding it soon(ish)!  ; )

Note: pull requests still welcome though.
