### ISSUE TITLE
Fails with concurrent clones of the same repository

### ISSUE THREAD

**Issue by rassie** [jonasmalacofilho/git-cache-http-server#5]
Running several concurrent clones of the same not-yet-cached repository results in an error, most probably "destination path already exists and is not an empty directory". This is probably expected given there isn't any kind of locking in place. 

```
export REPO=https://git-mirror.server.local/group/repo.git
git clone $REPO & git clone $REPO & git clone $REPO &
```
results in:

```
updating: fetching
updating: fetching
updating: fetching
updating: fetch failed, cloning
updating: fetch failed, cloning
updating: fetch failed, cloning

/usr/local/lib/node_modules/git-cache-http-server/bin/git-cache-http-server.js:91
					throw new js__$Boot_HaxeError("git clone exited with non-zero status: " + cerr.code);
					^
Error: git clone exited with non-zero status: 128
    at /usr/local/lib/node_modules/git-cache-http-server/bin/git-cache-http-server.js:91:12
    at ChildProcess.exithandler (child_process.js:278:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

**Comment by jonasmalacofilho** [comment]
Some locking has been implemented on the master branch (see bd2cbbd104bf19786d95a77ec1da79adf4c38a32).

Have you tried/can you try it?

**Comment by rassie** [comment]
Indeed, I have missed it. Will try on Monday, thanks!

**Comment by rassie** [comment]
Have run a couple of tests -- looking good! However, the installation process has been a rather cumbersome experience, since I couldn't install straight from the `master` tarball -- the `.js` file under `bin/` is not current. I've managed to compile it correctly, but still, might I suggest you do a 0.0.3 release when you get a chance? Would make life easier for those of us who see the need for Git caching :)

On a connected note, if you are interested, I've made a public Docker image which we are using for our deployment: https://github.com/kurzdigital/git-cache-http-server-docker/.

**Comment by jonasmalacofilho** [comment]
You're right, the pre-generated *.js is quite outdated.

I'll fix that and make a release soon.  I also found a remaining issue (for first-time repos)...

---

I'm very interested in the Docker image, thanks!  Do you mind if I eventually link to it?

And may I ask on what scale are you using this project and how's the experience (performance, reliability) been so far?

**Comment by rassie** [comment]
Yes, feel free to link to it, we could even integrate it into your repository; however you prefer.

Our environment: we are using Gitlab CI for our builds. Our Gitlab Runners are started in OpenShift and run exclusively with Docker. Since there is no build directory caching in such a setup, every step of the pipeline so far has been cloning the complete repository, which took about a minute with our connection and repository size. We've been looking for a way to cache those clones and have found a [feature](https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/698) in the upcoming version of the Gitlab Runner, which allows substituting the clone URL for something else -- so we are basically running a beta version of the runner together with `git-cache-http-server` now.

We are by no means slamming the server, but it is to be expected to get several clone request at the same time (parallel jobs), that's why getting lock support has been crucial for us. Just using git caching we could slash the pipeline time in one project from about 23 minutes to 15, cloning takes now about 10 seconds instead of a minute, no-op jobs are now taking the more or less expected 15 seconds instead of over a minute. In general: great stuff, however I wonder where it'd break :)

As for reliability, can't say for now. It's definitely a nuisance that the process dies on error, however it's no problem in OpenShift since the container just gets restarted whenever it does. I did get some errors about empty response from server on first clone, however this a non-issue after the cache is warmed up -- certainly something I can live with, especially for a software version 0.0.2.

As mentioned above, because of the new gitlab-runner feature, you might get a bit of attention in the coming days (they usually release on the 22th of every month). I'm happy so far and would push bug reports your way if I find something in production.
